name: Github Input Runner
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  push_to_registry:
    name: 动态取值
    runs-on: ubuntu-latest
    steps:
      - info
      - if: ${{ inputs.options }} == 'info'
        run: echo  The tags are ${{ inputs.options }}
        shell: bash
      - name: Set up JDK 8
      - if: ${{ inputs.options }} == 'debug'
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
