name: Github Input Runner
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      pom:
        description: 'pom 文件位置'
        required: true
        default: 'pom.xml'
        type: choice
        options:
          - pom.xml
          - XXX/pom.xml
          - XXX/XXX/pom.xml


jobs:
  push_to_registry:
    name: 动态取值
    runs-on: ubuntu-latest
    steps:
      - name: info
        if: ${{ inputs.pom.options }} == 'pom.xml'
        run: echo  The tags are ${{ inputs.pom.options }}
        shell: bash
      - name: Set up JDK 8
        if: ${{ inputs.pom.options }} == 'pom.xml'
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
