name: Github Input Runner
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      pom:
        description: 'pom 文件位置'
        required: true
        default: 'pom.xml'
        type: choice
        options:
          - pom.xml
          - XXX/pom.xml
          - XXX/XXX/pom.xml
      branch:
        description: '分支'
        required: true
        default: 'main'
        type: string

jobs:
  push_to_registry:
    name: 动态取值
    runs-on: ubuntu-latest
    steps:
      - name: info
        if: inputs.pom.options == 'pom.xml'
        run: echo  The tags are ${{ inputs.pom.options }}
        shell: bash
      - name: 获取分支
        if: inputs.branch == main
        run: echo  当前分支为 ${{ inputs.branch }}
        shell: bash